version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_USERNAME: root
    ports:
      - "3306:3306"
