# username for DB is 'root'
version: '2'

services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql