version: '3'

services:

  postgis:
    container_name: postgis
    image: postgis/postgis:14-3.2
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: toor # user postgres
