version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: unless-stopped
    environment:
      PGUSER: root
      PGPASSWORD: toor
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    driver: local