version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: toor # user postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/postgres
